name: AuraBot
version: '${project.version}'
main: github.regularrabbit05.anticheat.aurabot.Plugin
website: https://github.com/RegularRabbit05
depend:
  - NPCLib-Plugin
commands:
  auraPlayer:
    usage: /<command> <player>
    permission: watchdog.aurabot
    description: Test AuraBot on player
permissions:
  watchdog.bypass:
    description: Bypasses the checks
    default: op
  watchdog.notifications:
    description: Receives the alerts
    default: op